spring:
  config:
    activate:
      on-profile: management

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics, loggers
  endpoint:
    health:
      show-details: always
#  tracing:
#    enabled: true
#    sampling:
#        probability: 1
#  zipkin:
#    tracing:
#      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.description}
    version: ${spring.application.version}