spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    br.com.wells: debug
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework: info
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG

server:
  error:
    include-stacktrace: always