version: "3.8"

services:
  db-postgres:
    container_name: postgres-usuario
    restart: always
    user: postgres
    build:
      context: .
      dockerfile: ../../docker/imagem_base/Dockerfile.db-postgres #./imagem_base/Dockerfile.db-postgres
    environment:
      - POSTGRES_DB=wells-usuario
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 128M
    networks:
      - wells-usuario-rede

volumes:
  postgres_data:
networks:
  wells-usuario-rede:
    driver: bridge