spring:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@

  datasource:
    url: ${WELLS_PRODUTO_SPRING_DATASOURCE_URL:}
    username: ${WELLS_PRODUTO_SPRING_DATASOURCE_USERNAME:}
    password: ${WELLS_PRODUTO_SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

  profiles:
    active: ${PROFILE_ENVIRONMENT:prod}
    include: management, springdoc, app

logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"
  level:
    br.com.wells: info

server:
  error:
    include-stacktrace: never # desabilitar stacktrace no json que e retornado em caso de erro
  port: ${PORT:0}

