spring:
  cloud:

    discovery:
      enabled: true

    consul:
      host: ${CONSUL_HOST:http://localhost}
      port: ${CONSUL_PORT:8500}

      discovery:
        register-health-check: false
        prefer-ip-address: true
       #instance-id: ${spring.application.name}-${server.port}-${random.int[1,99]}
      enabled: true



