spring:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@

  cloud:

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: usuario-service
          uri: lb://wells-usuario
          predicates:
            - Path=/api/v1/usuarios/**, /api/v1/auth/**
          filters:
            - AuthenticationFilter

        # redireciona para o actuator do wells-usuario: http://localhost:8125/usuarios/actuator/health
        - id: usuario-service-actuator
          uri: lb://wells-usuario
          predicates:
            - Path=/usuarios/actuator/**
          filters:
            - StripPrefix=1


  profiles:
    active: ${PROFILE_ENVIRONMENT:default}
    include: actuator, app, service-registry

logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"
  level:
    root: DEBUG
    org.springframework.cloud.consul.discovery.web: DEBUG
    org.springframework.cloud.gateway : trace

server:
  port: ${PORT:8125}

app:
  endpoint:
    open-api-endpoints:
      - /api/v1/auth/login
      - /api/v1/auth/token
      - /api/v1/auth/validate
      - /api/v1/auth/login
