spring:
  application:
    name: @project.name@
    description: @project.description@
    version: @project.version@

  cloud:

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#
#        - id: usuario-service
#          uri: lb://wells-usuario
#          predicates:
#            - Path=/api/v1/usuarios/**, /api/v1/auth/**
#          filters:
#            - AuthenticationFilter
#
#        # redireciona para o actuator do wells-usuario: http://localhost:8125/usuarios/actuator/health
##        - id: usuario-service-actuator
##          uri: lb://wells-usuario
##          predicates:
##            - Path=/usuarios/actuator/**
##          filters:
##            - StripPrefix=1
#
#        - id: usuario-service-swagges
#          uri: lb://wells-usuario
#          predicates:
#              - Path=/usuarios/v3/api-docs/**, /usuarios/v3/api-docs/
#              - Method=GET


  profiles:
    active: ${PROFILE_ENVIRONMENT:default}
    include: actuator, springdoc, app, service-registry

logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"
  level:
    root: INFO
    org.springframework.cloud.consul.discovery.web: INFO
    org.springframework.cloud.gateway : trace

server:
  port: ${PORT:8125}


