spring:
  config:
    activate:
      on-profile: app
app:
  name: ${spring.application.name}
  description: ${spring.application.description}
  version: ${spring.application.version}

  authentication:
    validation-url: http://wells-usuario/api/v1/auth/validate?token=

  swagger:
    application:
      title: ${spring.application.name}
      description: ${spring.application.description}
      version: ${spring.application.version}