spring:
  config:
    activate:
      on-profile: springdoc

springdoc:
  #show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
#    groups:
#      enabled: true
    path: /v3/api-docs
