spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    br:
      com:
        fsales: debug
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG

server:
  error:
    include-stacktrace: on_param