spring:
  config:
    activate:
      on-profile: app
app:
  name: ${spring.application.name}
  api:
    security:
      jwt:
        withIssuer: wells-usuario
        public-key: classpath:app-public.pem
        private-key: classpath:app-private.pem

  swagger:
    url: http://localhost:8125 # url do gateway
    application:
      title: ${spring.application.name}
      description: ${spring.application.description}
      version: ${spring.application.version}